# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: store_development
  pool: 5
  username: postdream
  password: test1234

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: store_test
  pool: 5
  username: postdream
  password: test1234